import type { WebNode, WebStructureGraph } from "@/mirrorcraft/web-structure/types";
import { buildWeb360Snapshot } from "@/mirrorcraft/web-structure/graph";
import type { ChangeWatchResult, ImpactReport, MirrorCommand, MirrorCommandName, MirrorTarget, MirrorTargetKind, TargetContext, TargetResolution, TargetResolutionCandidate } from "@/mirrorcraft/target-studio/types";
export * from "@/mirrorcraft/target-studio/types";
const KIND_MAP:Partial<Record<WebNode["kind"],MirrorTargetKind>>={page:"page",route:"route",asset:"asset",function:"interaction",container:"component",child:"component",content:"dom"};
function unique<T>(v:T[]):T[]{return [...new Set(v)]}
function metadataStrings(n:WebNode,k:string):string[]{const v=n.metadata?.[k];if(typeof v==="string")return[v];if(Array.isArray(v))return v.filter((x):x is string=>typeof x==="string");return[]}
function metadataNumbers(n:WebNode,k:string):number[]{const v=n.metadata?.[k];if(typeof v==="number")return[v];if(Array.isArray(v))return v.filter((x):x is number=>typeof x==="number");return[]}
function stable(value:unknown):string{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value)}
export function targetFromWebNode(g:WebStructureGraph,n:WebNode):MirrorTarget{const s=buildWeb360Snapshot(g,n.id);return{id:n.id,kind:KIND_MAP[n.kind]??"source",webNodeKind:n.kind,label:n.label,route:n.route,file:n.sourcePath,sourceRange:n.sourceLine?{startLine:n.sourceLine,endLine:n.sourceLine}:undefined,selector:metadataStrings(n,"selector")[0],symbol:metadataStrings(n,"symbol")[0],dependencies:unique(s?.outgoing.map(e=>e.to)??[]),dependents:unique(s?.incoming.map(e=>e.from)??[]),viewports:unique(metadataNumbers(n,"viewports")),findingIds:unique(metadataStrings(n,"findingIds")),evidenceIds:unique(metadataStrings(n,"evidenceIds")),metadata:n.metadata}}
export function resolveTarget(g:WebStructureGraph,q:{id?:string;route?:string;sourcePath?:string;selector?:string;label?:string},t=.8):TargetResolution{const c:TargetResolutionCandidate[]=Object.values(g.nodes).map(n=>{let score=0;const reasons:string[]=[];if(q.id&&n.id===q.id){score+=1;reasons.push("exact-id")}if(q.route&&n.route===q.route){score+=.8;reasons.push("exact-route")}if(q.sourcePath&&n.sourcePath===q.sourcePath){score+=.8;reasons.push("exact-source")}if(q.label&&n.label===q.label){score+=.6;reasons.push("exact-label")}if(q.selector&&metadataStrings(n,"selector").includes(q.selector)){score+=.9;reasons.push("exact-selector")}return{target:targetFromWebNode(g,n),confidence:Math.min(1,score),reasons}}).filter(x=>x.confidence>0).sort((a,b)=>b.confidence-a.confidence||a.target.id.localeCompare(b.target.id));const top=c[0]??null,second=c[1]??null,ambiguous=Boolean(top&&second&&Math.abs(top.confidence-second.confidence)<.1);return{selected:top&&top.confidence>=t&&!ambiguous?top:null,candidates:c,ambiguous}}
export function buildTargetContext(g:WebStructureGraph,id:string):TargetContext|null{const s=buildWeb360Snapshot(g,id);if(!s)return null;const related=unique([...s.parents,...s.children,...s.ancestors,...s.descendants,...s.incoming.map(e=>g.nodes[e.from]),...s.outgoing.map(e=>g.nodes[e.to])].filter((n):n is WebNode=>Boolean(n))),target=targetFromWebNode(g,s.focus),all=[s.focus,...related];return{target,sourceFiles:unique(all.flatMap(n=>n.sourcePath?[n.sourcePath]:[])),styles:unique(all.flatMap(n=>metadataStrings(n,"styles"))),assets:unique(all.filter(n=>n.kind==="asset").map(n=>n.id)),routes:unique(all.flatMap(n=>n.route?[n.route]:[])),interactions:unique(all.filter(n=>n.kind==="function"||n.kind==="api").map(n=>n.id)),affectedTargets:unique(related.map(n=>n.id)),affectedViewports:unique(all.flatMap(n=>metadataNumbers(n,"viewports"))).sort((a,b)=>a-b),evidence:unique(all.flatMap(n=>metadataStrings(n,"evidenceIds"))),findings:unique(all.flatMap(n=>metadataStrings(n,"findingIds"))),confidence:1,unresolved:[]}}
export function buildImpactReport(g:WebStructureGraph,id:string):ImpactReport|null{const c=buildTargetContext(g,id);if(!c)return null;const nodes=[c.target,...c.affectedTargets.map(x=>g.nodes[x]).filter(Boolean).map(n=>targetFromWebNode(g,n))],tests=unique(nodes.flatMap(t=>{const x=t.metadata?.tests;return Array.isArray(x)?x.filter((i):i is string=>typeof i==="string"):[]}));return{targetId:id,affectedFiles:c.sourceFiles,affectedComponents:unique(nodes.filter(t=>t.kind==="component").map(t=>t.id)),affectedRoutes:c.routes,affectedInteractions:c.interactions,affectedViewports:c.affectedViewports,affectedTests:tests,affectedFindings:c.findings,requiresBuild:c.sourceFiles.length>0,requiresCapture:c.routes.length>0&&c.affectedViewports.length>0,requiresBehaviorTest:c.interactions.length>0}}
function emptyImpact():ImpactReport{return{targetId:"change-set",affectedFiles:[],affectedComponents:[],affectedRoutes:[],affectedInteractions:[],affectedViewports:[],affectedTests:[],affectedFindings:[],requiresBuild:false,requiresCapture:false,requiresBehaviorTest:false}}
export function watchGraphChanges(before:WebStructureGraph,after:WebStructureGraph):ChangeWatchResult{const beforeIds=Object.keys(before.nodes),afterIds=Object.keys(after.nodes),added=afterIds.filter(id=>!before.nodes[id]).sort(),removed=beforeIds.filter(id=>!after.nodes[id]).sort(),changed=afterIds.filter(id=>before.nodes[id]&&stable(before.nodes[id])!==stable(after.nodes[id])).sort();const ids=unique([...added,...removed,...changed]),reports=ids.map(id=>buildImpactReport(after,id)??buildImpactReport(before,id)).filter((x):x is ImpactReport=>Boolean(x)),impact=reports.reduce((a,r)=>({targetId:"change-set",affectedFiles:unique([...a.affectedFiles,...r.affectedFiles]),affectedComponents:unique([...a.affectedComponents,...r.affectedComponents]),affectedRoutes:unique([...a.affectedRoutes,...r.affectedRoutes]).sort(),affectedInteractions:unique([...a.affectedInteractions,...r.affectedInteractions]),affectedViewports:unique([...a.affectedViewports,...r.affectedViewports]).sort((x,y)=>x-y),affectedTests:unique([...a.affectedTests,...r.affectedTests]).sort(),affectedFindings:unique([...a.affectedFindings,...r.affectedFindings]),requiresBuild:a.requiresBuild||r.requiresBuild,requiresCapture:a.requiresCapture||r.requiresCapture,requiresBehaviorTest:a.requiresBehaviorTest||r.requiresBehaviorTest}),emptyImpact());const required=ids.length>0;return{addedTargetIds:added,removedTargetIds:removed,changedTargetIds:changed,impact,revalidation:{required,fullProject:false,routes:impact.affectedRoutes,viewports:impact.affectedViewports,tests:impact.affectedTests,visual:impact.requiresCapture,structural:required,behavioral:impact.requiresBehaviorTest,build:impact.requiresBuild}}}
export function createMirrorCommand(input:{command:MirrorCommandName;targetId:string;mode?:MirrorCommand["mode"];intent?:string;preserve?:string[];verification?:MirrorCommand["verification"]}):MirrorCommand{const mode=input.mode??(input.command==="modify"||input.command==="rectify"?"virtual":"read"),s=JSON.stringify({command:input.command,targetId:input.targetId,mode,intent:input.intent??""});let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return{id:`mc-${(h>>>0).toString(16).padStart(8,"0")}`,command:input.command,targetId:input.targetId,mode,intent:input.intent,preserve:input.preserve,verification:input.verification}}
